SistemaVendas/Controllers/ClienteController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using SistemaVendas.Dtos;
using SistemaVendas.Models;
using SistemaVendas.Repositorys;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace SistemaVendas.Controllers
{
    public class ClienteController : Controller
    {
        #region Atributos
        private readonly IClienteRepository _repository;
        private readonly IMapper _mapper;
        #endregion Atributos

        #region Construtor
        public ClienteController(IClienteRepository repository, IMapper mapper)
        {
            _repository = repository;
            _mapper = mapper;
        }
        #endregion Construtor

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            try
            {
                var clientesModel = await _repository.GetAllClientes();

                /* Carregando uma Model no Dto manualmente. Usando o automapper da pra fazer automaticamente, igual exemplo abaixo descomentado
                var listaClientesDto  = new List<ClienteDto>();
                foreach (var item in clientes)
                {
                    var clienteDto = new ClienteDto()
                    { 
                      Id = item.Id, Nome = item.Nome, 
                      CpfCnpj = item.CpfCnpj, Email = item.Email, Senha = item.Senha 
                    };
                    listaClientesDto.Add(clienteDto);
                } */

                var clientesDto = _mapper.Map<List<ClienteDto>>(clientesModel);
                return View(clientesDto);
            }
            catch
            {
                return View("Error");                
            }            
        }

        #region Add
        [HttpGet]
        public IActionResult Add()
        {
            return View("Add");
        }

        [HttpPost]
        public async Task<IActionResult> Post(ClienteDto clienteDto)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var clienteModel = _mapper.Map<ClienteModel>(clienteDto);
                    _repository.Add(clienteModel);
                    if (await _repository.SaveChanges())                    
                        return RedirectToAction("Index");                    
                }
                return View("Add", clienteDto);
            }
            catch
            {
                return View("Error");
            }
        }
        #endregion Add

        #region Update
        public async Task<IActionResult> Update(int idCliente) //Este parametro tem que ter o mesmo nome que colocou asp-route-"idCliente" na Index 
        {            
            try
            {                
                var clienteModel = await _repository.GetClientePorId(idCliente);
                if (clienteModel != null)
                {
                    var clienteDto = _mapper.Map<ClienteDto>(clienteModel);
                    return View(clienteDto);
                }

                return View("Update");
            }
            catch 
            {
                return View("Error");
            }
        }

        [HttpPost]
        public async Task<IActionResult> Put(ClienteDto clienteDto)
        {
            try 
            {                
                if (ModelState.IsValid)
                {
                    var clienteModel = _mapper.Map<ClienteModel>(clienteDto);
                    var clienteDB = await _repository.GetClientePorId(clienteModel.Id);
                    if (clienteDB != null)
                        _repository.Update(clienteModel);

                    if(await _repository.SaveChanges())
                        return RedirectToAction("Index");
                }                
                return View("Update", clienteDto);
            } 
            catch
            {
                return View("Error");
            }            
        }
        #endregion Update

        #region Delete
        public async Task<IActionResult> Delete(int idCliente) 
        {
            try
            {
                var clienteModel = await _repository.GetClientePorId(idCliente);
                var clienteDto = _mapper.Map<ClienteDto>(clienteModel);
                return View(clienteDto);
            }
            catch
            {
                return View("Error");
            }      
        }

        public async Task<IActionResult> DeleteConfirm(int idCliente)
        {
            try
            {
                var clienteModel = await _repository.GetClientePorId(idCliente);
                if (clienteModel != null)
                {
                    _repository.Delete(clienteModel);
                    if(await _repository.SaveChanges());
                        return RedirectToAction("Index");
                }
            }
            catch
            {   
            }
            return View("Error");
        }
        #endregion Delete

    }
}

SistemaVendas/Controllers/ProdutoController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using SistemaVendas.Dtos;
using SistemaVendas.Models;
using SistemaVendas.Repositorys;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using static SistemaVendas.Enums.Enumeradores;

namespace SistemaVendas.Controllers
{
    public class ProdutoController : Controller
    {
        private readonly IProdutoRepository _repository;
        private readonly IMapper _mapper;

        public ProdutoController(IProdutoRepository repository, IMapper mapper)
        {
            _repository = repository;
            _mapper = mapper;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            try
            {
                var produtosModel = await _repository.GetAllProdutos();
                var produtosDto = _mapper.Map<List<ProdutoDto>>(produtosModel);
                return View(produtosDto);
            }
            catch
            {
                return View("Error");
            }
        }

        #region Add
        public IActionResult Add()
        {
            return View("Add");
        }

        [HttpPost]
        public async Task<IActionResult> Post(ProdutoDto produtoDto)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var produtoModel = _mapper.Map<ProdutoModel>(produtoDto);                    
                    produtoModel.UnidadeMedida = ((UnidadeMedida)Convert.ToInt32(produtoModel.UnidadeMedida)).ToString();
                    _repository.Add(produtoModel);
                    if (await _repository.SaveChanges())
                        return RedirectToAction("Index");
                }
                return View("Add", produtoDto);
            }
            catch
            {
                return View("Error");
            }
        }
        #endregion Add

        #region Update
        public async Task<IActionResult> Update(int idProduto)
        {
            try
            {
                var produtoModel = await _repository.GetProdutoPorId(idProduto);                
                if (produtoModel != null)
                {
                    var produtoDto = _mapper.Map<ProdutoDto>(produtoModel);
                    ViewBag.UnidadeMedida = produtoDto.UnidadeMedida;        
                    return View(produtoDto);
                }
                return View();
            }
            catch
            {
                return View("Error");
            }
        }

        [HttpPost]
        public async Task<IActionResult> Put(ProdutoDto produtoDto)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var produtoModel = _mapper.Map<ProdutoModel>(produtoDto);
                    produtoModel.UnidadeMedida = ((UnidadeMedida)Convert.ToInt32(produtoModel.UnidadeMedida)).ToString();
                    var produtoDB = await _repository.GetProdutoPorId(produtoModel.Id);
                    if (produtoDB != null)
                    {
                        _repository.Update(produtoModel);
                        if(await _repository.SaveChanges())                        
                            return RedirectToAction("Index");                        
                    }
                }
                return View("Update", produtoDto);
            }
            catch 
            {
                return View("Error");
            }
        }
        #endregion Update

        #region Delete
        public async Task<IActionResult> Delete(int idProduto)
        {
            try
            {
                var produtoModel = await _repository.GetProdutoPorId(idProduto);
                var produtoDto = _mapper.Map<ProdutoDto>(produtoModel);
                return View(produtoDto);
            }
            catch
            {
                return View("Error");
            }
        }

        public async Task<IActionResult> DeleteConfirm(int idProduto)
        {
            try
            {
                var produtoModel = await _repository.GetProdutoPorId(idProduto);
                if(produtoModel != null)
                {
                    _repository.Delete(produtoModel);
                    if(await _repository.SaveChanges())
                        return RedirectToAction("Index");
                }
            }
            catch
            {
            }

            return View("Error");
        }
        #endregion Delete
    }
}

SistemaVendas/Controllers/RelatorioController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using SistemaVendas.Dtos;
using SistemaVendas.Models;
using SistemaVendas.Repositorys;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace SistemaVendas.Controllers
{
    public class RelatorioController : Controller
    {
        private readonly IVendaRepository _vendaRepository;
        private readonly IGraficoVendaRepository _graficoVendaRepository;
        private readonly IMapper _mapper;

        public RelatorioController(IVendaRepository vendaRepository, IGraficoVendaRepository graficoVendaRepository, IMapper mapper)
        {
            _vendaRepository = vendaRepository;
            _graficoVendaRepository = graficoVendaRepository;
            _mapper = mapper;
        }

        public IActionResult Index()
        {
            return View("Index");
        }
        
        [HttpGet]
        public async Task<IActionResult> VendaPeriodo(DateTime dataDe, DateTime dataAte) 
        {
            try
            {
                var vendasModel = new List<VendaModel>();
                if (dataDe != new DateTime() || dataAte != new DateTime())
                    vendasModel = await _vendaRepository.GetVendaPorPeriodo(dataDe, dataAte);
                else
                    vendasModel = await _vendaRepository.GetAllVendas();

                var vendasDto = _mapper.Map<List<VendaDto>>(vendasModel);                
                return View(vendasDto);
            }
            catch 
            {
            }        
            return View("Error");
        }

        [HttpGet]
        public async Task<IActionResult> Grafico()
        {
            var listaProdutosVendidos = await _graficoVendaRepository.GetSomaProdutoVendido();
            string valores = null, labels = null, cores = null;
            var random = new Random();

            foreach (var item in listaProdutosVendidos)
            {
                valores += $"{item.QuantidadeVendida},";
                labels += $"'{item.DescricaoProduto}',";
                //random nas cores
                cores += $"'{string.Format("#{0:X6}", random.Next(0x1000000))}',";
            }
            ViewBag.Valores = valores;
            ViewBag.Labels = labels;
            ViewBag.Cores = cores;

            return View("Grafico");
        }
    }
}

SistemaVendas/Controllers/VendaController.cs
using Microsoft.AspNetCore.Mvc;
using SistemaVendas.Models;
using SistemaVendas.Repositorys;
using System;
using Microsoft.AspNetCore.Http;
using System.Threading.Tasks;
using AutoMapper;
using SistemaVendas.Dtos;
using System.Collections.Generic;

namespace SistemaVendas.Controllers
{
    public class VendaController : Controller
    {
        private readonly IVendaRepository _repository;
        private readonly IClienteRepository _clienteRepository;
        private readonly IProdutoRepository _produtoRepository;
        private readonly IHttpContextAccessor _contextAccessor;
        private readonly IMapper _mapper;

        public VendaController(IVendaRepository repository, IClienteRepository clienteRepository, 
            IProdutoRepository produtoRepository, IHttpContextAccessor httpContextAccessor, IMapper mapper)
        {
            _repository = repository;
            _clienteRepository = clienteRepository;
            _produtoRepository = produtoRepository;
            _contextAccessor = httpContextAccessor;
            _mapper = mapper;
        }

        public async Task<IActionResult> Index()
        {
            try
            {
                var vendasModel = await _repository.GetAllVendas();
                var vendasDto = _mapper.Map<List<VendaDto>>(vendasModel);
                return View(vendasDto);
            }
            catch 
            {
            }
            return View("Error");
        }

        #region Add
        public async Task<IActionResult> Add()
        {
            try
            {
                var clientesModel = await _clienteRepository.GetAllClientes();
                var produtosModel = await _produtoRepository.GetAllProdutosComEstoque();
                ViewBag.ListaClientes = _mapper.Map<List<ClienteDto>>(clientesModel);
                ViewBag.ListaProdutos = _mapper.Map<List<ProdutoDto>>(produtosModel);
                return View("Add");
            }
            catch
            {
            }
            return View("Error");
        }

        [HttpPost]
        public async Task<IActionResult> Post(VendaDto vendaDto)
        {
            try
            {
                if(ModelState.IsValid)
                {
                    var vendaModel = _mapper.Map<VendaModel>(vendaDto);
                    var vendaRegraNegocio = new VendaModel(_repository, _produtoRepository);
                    var idUserLogado = Convert.ToInt32(_contextAccessor.HttpContext.Session.GetString("idUsuarioLogado"));
                    if (await vendaRegraNegocio.IncluiVendaEAlteraQuantidadeProduto(vendaModel, idUserLogado))
                        return RedirectToAction("Index");                    
                }
                else
                {
                    ViewBag.ListaClientes = _clienteRepository.GetAllClientes();
                    ViewBag.ListaProdutos = _produtoRepository.GetAllProdutosComEstoque();
                    return View("Add", vendaDto);
                }
            }
            catch 
            {
            }
            return View("Error");
        }
        #endregion Add

        #region Delete
        public async Task<IActionResult> Delete(int idVenda)
        {
            try
            {
                var vendaModel = await _repository.GetVendaPorId(idVenda);
                var vendaDto = _mapper.Map<VendaDto>(vendaModel);
                return View(vendaDto);
            }
            catch
            {
            }
            return View("Error");
        }
                
        public async Task<IActionResult> DeleteConfirm(int idVenda)
        {
            try
            {
                var vendaModel = await _repository.GetVendaPorId(idVenda);
                if(vendaModel != null)
                {
                    var vendaRegraNegocio = new VendaModel(_repository, _produtoRepository);
                    if (await vendaRegraNegocio.ExcluiVendaEAlteraQuantidadeProduto(vendaModel))
                        return RedirectToAction("Index");
                    else
                        return View("Error");                    
                }
            }
            catch
            {
            }
            return View("Error");
        }
        #endregion Delete
    }
}

SistemaVendas/Views/Home/Login.cshtml
@using SistemaVendas.Dtos;
@model VendedorDto

@{
    ViewData["Title"] = "Login";
    Layout = null; 
    //Cancela o uso do Layout template, pq fiz a validação no _Layout para retornar para essa pagina de Login senão tiver usuário logado
}

@* Precisei referenciar esses dois abaixo, pois como cancelei o Layout por causa do loop infito que estava acontecendo, tive que referencia-los *@
<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
<link rel="stylesheet" href="~/css/site.css" />


<main class="login-form">
    <div class="cotainer">
        <div class="row justify-content-center">
            <div class="col-md-5">
                <div class="card">
                    <div class="card-header">Sign In</div>
                    <div class="card-body">
                        <form asp-controller="Home" asp-action="Login" method="post">
                            <div class="form-group row">
                                <label for="email_address" class="col-md-4 col-form-label text-md-right">E-Mail</label>
                                <div class="col-md-6">
                                    <input type="email" class="form-control" asp-for="Email" />
                                    @Html.ValidationMessageFor(x => x.Email)
                                    @* Existe essa forma de usar a validação da model tbm e acredito ser mais facil, pois ja usa o
                                    razor e bootstrap no texto para colocar a cor
                                    <span asp-validation-for="Email" class="text-danger"></span> *@
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="password" class="col-md-4 col-form-label text-md-right">Senha</label>
                                <div class="col-md-6">
                                    <input type="password" class="form-control" asp-for="Senha">
                                    <span asp-validation-for="Senha" class="text-danger"></span>
                                </div>
                                <div class="col-md-6 offset-md-4">
                                    @{
                                        if (TempData["ErrorLogin"] != null)
                                        {
                                            var erro = TempData["ErrorLogin"].ToString();
                                            <h5 class="text-danger">@erro</h5>
                                        }
                                    }
                                </div>
                            </div>

                            <div class="form-group row">
                                <div class="col-md-6 offset-md-4">
                                    <div class="checkbox">
                                        <label>
                                            <input type="checkbox" name="remember"> Lembre-me
                                        </label>
                                    </div>
                                </div>
                            </div>

                            <div class="form-group row">
                                <div class="col-md-6 offset-md-4">
                                    <button type="submit" class="btn btn-primary">Entrar</button>
                                    <a href="#" class="btn btn-link">Esqueceu sua senha?</a>
                                </div>
                            </div>

                            <div class="form-group row">
                                <div class="col-md-6 offset-md-4">
                                    <p>Não é cadastrado? <a href="#!">Cadastre-se</a></p>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>

SistemaVendas/Views/Home/Menu.cshtml
@{
    ViewData["Title"] = "Menu";
}
<br />
<div class="row" style="font-family:Arial; font-size:medium; color:#242424">
    <div class="col-lg-4" style="text-align:center">
        <div>
            <a asp-controller="Cliente" asp-action="Index"><img src="~/images/clientes.png" width="150" height="150" style="text-align:center" /></a>
        </div>
        <span>Cadastro de Clientes</span>
    </div>

    <div class="col-lg-4" style="text-align:center">
        <div>
            <a asp-controller="Vendedor" asp-action="Index"><img src="~/images/vendedores.png" width="150" height="150" /></a>
        </div>
        <span>Cadastro de Vendedores</span>
    </div>

    <div class="col-lg-4" style="text-align:center"  >
        <div>
            <a asp-controller="Produto" asp-action="Index"><img src="~/images/produtos.png" width="150" height="150" /></a>
        </div>
        <span>Cadastro de Produtos</span>
    </div>

</div>
<br />
<br />
<div class="row" style="font-family:Arial; font-size:medium; color:#242424">
    <div class="col-lg-4" style="text-align:center"  >
        <div>
            <a asp-controller="Venda" asp-action="Index"><img src="~/images/vendas.png" width="150" height="150" /></a>
        </div>
        <span>Registro de Vendas</span>
    </div>

    <div class="col-lg-4" style="text-align:center"  >
        <div>
            <a asp-controller="Relatorio" asp-action="Index"><img src="~/images/relatorios.png" width="150" height="150" /></a>
        </div>
        <span>Relatórios</span>
    </div>

    <div class="col-lg-4" style="text-align:center"  >
        <div>
            <img src="~/images/configuracoes.png" width="150" height="150" />
        </div>
        <span>Configurações</span>
    </div>
</div>