SistemaVendas/Controllers/VendedorController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using SistemaVendas.Dtos;
using SistemaVendas.Models;
using SistemaVendas.Repositorys;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace SistemaVendas.Controllers
{
    public class VendedorController : Controller
    {
        private readonly IVendedorRepository _repository;
        private readonly IMapper _mapper;

        public VendedorController(IVendedorRepository repository, IMapper mapper)
        {
            _repository = repository;
            _mapper = mapper;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            try
            {
                var vendedoresModel = await _repository.GetAllVendedores();
                var vendedoresDto = _mapper.Map<List<VendedorDto>>(vendedoresModel);
                return View(vendedoresDto);
            }
            catch 
            {
                return View("Error");
            }
        }

        #region Add
        public IActionResult Add()
        {
            return View("Add");
        }

        [HttpPost]
        public async Task<IActionResult> Post(VendedorDto vendedor)
        {
            try
            {
                if(ModelState.IsValid)
                {
                    var vendedorModel = _mapper.Map<VendedorModel>(vendedor);
                    _repository.Add(vendedorModel);
                    if(await _repository.SaveChanges())
                        return RedirectToAction("Index");
                }
                return View("Add", vendedor);
            }
            catch
            {
                return View("Error");
            }
        }
        #endregion Add

        #region Update
        public async Task<IActionResult> Update(int idVendedor) //Este parametro tem que ter o mesmo nome que colocou asp-route-"idVendedor" na Index 
        {
            try
            {
                var vendedorModel = await _repository.GetVendedorPorId(idVendedor);                
                if (vendedorModel != null)
                {
                    var vendedorDto = _mapper.Map<VendedorDto>(vendedorModel);
                    return View(vendedorDto);
                }
                
                return View();
            }
            catch 
            {
                return View("Error");
            }
        }

        [HttpPost]
        public async Task<IActionResult> Put(VendedorDto vendedorDto)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var vendedorModel = _mapper.Map<VendedorModel>(vendedorDto);
                    var vendedorDB = await _repository.GetVendedorPorId(vendedorModel.Id);                    
                    if (vendedorDB != null)
                    {
                        _repository.Update(vendedorModel);
                        if (await _repository.SaveChanges())
                            return RedirectToAction("Index");
                    }
                }
                return View("Update", vendedorDto);
            }
            catch 
            {
                return View("Error");
            }
        }
        #endregion Update

        #region Delete
        public async Task<IActionResult> Delete(int idVendedor)
        {
            try
            {
                var vendedorModel = await _repository.GetVendedorPorId(idVendedor);
                var vendedorDto = _mapper.Map<VendedorDto>(vendedorModel);
                return View(vendedorDto);
            }
            catch 
            {
                return View("Error");
            }
        }

        public async Task<IActionResult> DeleteConfirm(int idVendedor)
        {
            try
            {
                var vendedorModel = await _repository.GetVendedorPorId(idVendedor);
                if (vendedorModel != null)
                {
                    _repository.Delete(vendedorModel);
                    if (await _repository.SaveChanges())
                        return RedirectToAction("Index");
                }                
            }
            catch 
            {                
            }

            return View("Error");
        }
        #endregion Delete
    }
}

SistemaVendas/Views/Vendedor/Add.cshtml
@using SistemaVendas.Dtos;
@model VendedorDto

@{
    ViewData["Title"] = "Adicionar Vendedor";
}
<meta charset="utf-8" />

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">

            <div class="text-center">
                <h1 class="display-4">Adicionar Vendedor</h1>
            </div>

            <form class="row g-3" asp-controller="Vendedor" asp-action="Post" method="Post">
                <div class="col-12">
                    <label for="text" class="col-form-label">Nome</label>
                    <input type="text" class="form-control" asp-for="Nome" placeholder="Inseri o nome"/>
                    <span asp-validation-for="Nome" class="text-danger"></span>
                </div>

                <div class="col-12">
                    <label form="text" class="col-form-label">@Html.DisplayNameFor(m => m.Email)</label>
                    <input type="text" class="form-control" asp-for="Email" placeholder="Insira o e-mail" />
                    <span asp-validation-for="Email" class="text-danger"></span>
                </div>

                <div class="col-6">
                    <label form="text" class="col-form-label">Senha</label>
                    <input type="password" class="form-control" asp-for="Senha" placeholder="Insira uma senha" />
                    <span asp-validation-for="Senha" class="text-danger"></span>
                </div>

                <div class="col-6">
                    <label for="text" class="col-form-label">Confirmar Senha</label>
                    <input type="password" class="form-control" asp-for="ComparaSenha" />
                    <span asp-validation-for="ComparaSenha" class="text-danger"></span>
                </div>
                <br />
                <br />
                <br />
                <br />

                <div class="col-6">
                    <button type="submit" class="btn btn-primary" value="Post">Adicionar</button>
                    <a class="btn btn-secondary" role="button" asp-controller="Vendedor" asp-action="Index">Voltar</a>
                </div>

            </form>
        </div>
    </div>
</div>

SistemaVendas/Views/Vendedor/Delete.cshtml
@using SistemaVendas.Dtos;
@model VendedorDto

@{
    ViewData["Title"] = "Excluir Vendedor";
}
<meta charset="utf-8" />

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">

            <div class="text-center">
                <h4 class="display-4">Excluir Vendedor</h4>
            </div>

            <div class="text-left">
                <h3>Deseja realmente excluir o vendedor: <b> @Html.DisplayFor(m => m.Nome)</b> ?</h3>
            </div>

            <form class="row g-3">
                <div class="col-6">
                    <a class="btn btn-primary" role="button" asp-controller="Vendedor" asp-action="DeleteConfirm" asp-route-idVendedor="@Model.Id">Confirmar</a>
                    <a class="btn btn-secondary" role="button" asp-controller="Vendedor" asp-action="Index">Voltar</a>
                </div>
            </form>
        </div>
    </div>
</div>

SistemaVendas/Views/Vendedor/Index.cshtml
@using SistemaVendas.Dtos;
@model List<VendedorDto>

@{
    ViewData["Title"] = "Vendedor";
}
<meta charset="utf-8" />

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">

            <div class="d-grid gap-2 d-md-flex justify-context-md-start">
                <a class="btn btn-primary" role="button" asp-controller="Vendedor" asp-action="Add">Adicionar Vendedor</a>
            </div>
            <br />

            <div class="text-center">
                <h4 class="display-4">Lista de Vendedores</h4>
            </div>

            <table class="table text-center">
                <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Nome</th>
                        <th scope="col">E-mail</th >
                    </tr>
                </thead>
                <tbody>

                    @if(Model != null && Model.Any())
                    {
                        foreach (var vendedor in Model)
                        {
                            <tr>
                                <th scope="row">@vendedor.Id</th>
                                <td>@vendedor.Nome</td>
                                <td>@vendedor.Email</td>
                                <td>
                                    <div class="btn-group" role="group">
                                        <a class="btn btn-primary" role="button" asp-controller="Vendedor" asp-action="Update" asp-route-idVendedor="@vendedor.Id">Editar</a>
                                        <a class="btn btn-danger" role="button" asp-controller="Vendedor" asp-action="Delete" asp-route-idVendedor="@vendedor.Id">Excluir</a>
                                    </div>
                                </td>
                            </tr>
                        }
                    }

                </tbody>
            </table>

        </div>
    </div>
</div>

SistemaVendas/Views/Vendedor/Update.cshtml
@using SistemaVendas.Dtos;
@model VendedorDto

@{
    ViewData["Title"] = "Alterar Vendedor";
}
<meta charset="utf-8" />

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">

            <div class="text-center">
                <h4 class="display-4">Alterar Vendedor</h4>
            </div>

            <form class="row g-3" asp-controller="Vendedor" asp-action="Put" method="Post">
                <input type="hidden" asp-for="Id" />

                <div class="col-12">
                    <label for="text" class="col-form-label">Nome</label>
                    <input type="text" class="form-control" asp-for="Nome"/>
                    <span asp-validation-for="Nome" class="text-danger"></span>
                </div>

                <div class="col-12">
                    <label for="text" class="col-form-label">@Html.DisplayNameFor(m => m.Email)</label>
                    <input type="text" class="form-control" asp-for="Email" />
                    <span asp-validation-for="Email" class="text-danger"></span>
                </div>

                <div class="col-6">
                    <label for="text" class="col-form-label">Senha</label>
                    <input type="password" class="form-control" asp-for="Senha" />
                    <span asp-validation-for="Senha" class="text-danger"></span>
                </div>

                <div class="col-6">
                    <label for="text" class="col-form-label">Confirmar Senha</label>
                    <input type="password" class="form-control" asp-for="ComparaSenha" />
                    <span asp-validation-for="ComparaSenha" class="text-danger"></span>
                </div>
                <br />
                <br />
                <br />
                <br />

                <div class="col-12">
                    <button type="submit" class="btn btn-primary" value="Put">Editar</button>
                    <a class="btn btn-secondary" role="button" asp-controller="Vendedor" asp-action="Index">Voltar</a>
                </div>

            </form>
        </div>
    </div>
</div>